workflows:
  ios_build:
    name: iOS Build
    max_build_duration: 60
    environment:
      flutter:
        version: "stable"  # Use "stable" for the latest stable version or specify a specific version
      xcode: "latest"  # Use the version that matches your project needs
      cocoapods: "default"
    scripts:
      - name: Build iOS App
        script: flutter build ios --release --flavor ios-production -t lib/main_prod.dart
    artifacts:
      - build/ios/iphoneos/*.ipa
