workflows:
  ios_build:
    name: iOS Build
    max_build_duration: 60
    environment:
      flutter:
        version: "stable"
      xcode: "latest"
      cocoapods: "default"
    scripts:
      - name: Build iOS App
        script: flutter build ios --release -t lib/main.dart
    artifacts:
      - build/ios/iphoneos/*.ipa
